### PR TITLE
Switching to 0.12 SDK

### PR DESCRIPTION
**Pull request by gordonbondon**
More and more providers are adding support for 0.12 SDK. Due to complex structures in this provider we thought it would be easier to use it with 0.12 tf.

When running full acceptance tests with new SDK i've found a couple of issues. I'll file them as separate PRs.

PRs required to pass all acceptance tests with new SDK: #129 #128 #127 

<details><summary>Acceptance tests:</summary>
<p>

```
→ GOFLAGS=-mod=vendor make testacc TEST=./pagerduty
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./pagerduty -v  -timeout 120m
=== RUN   TestConfigEmptyToken
--- PASS: TestConfigEmptyToken (0.00s)
=== RUN   TestConfigSkipCredsValidation
2019/04/19 19:02:07 [INFO] PagerDuty client configured
--- PASS: TestConfigSkipCredsValidation (0.00s)
=== RUN   TestAccDataSourcePagerDutyEscalationPolicy_Basic
--- PASS: TestAccDataSourcePagerDutyEscalationPolicy_Basic (16.28s)
=== RUN   TestAccDataSourcePagerDutyExtensionSchema_Basic
--- PASS: TestAccDataSourcePagerDutyExtensionSchema_Basic (8.53s)
=== RUN   TestAccDataSourcePagerDutySchedule_Basic
--- PASS: TestAccDataSourcePagerDutySchedule_Basic (14.24s)
=== RUN   TestAccDataSourcePagerDutyTeam_Basic
--- PASS: TestAccDataSourcePagerDutyTeam_Basic (9.61s)
=== RUN   TestAccDataSourcePagerDutyUser_Basic
--- PASS: TestAccDataSourcePagerDutyUser_Basic (11.94s)
=== RUN   TestAccDataSourcePagerDutyVendor_Basic
--- PASS: TestAccDataSourcePagerDutyVendor_Basic (8.26s)
=== RUN   TestAccDataSourcePagerDutyVendor_ExactMatch
--- PASS: TestAccDataSourcePagerDutyVendor_ExactMatch (8.39s)
=== RUN   TestAccPagerDutyEscalationPolicy_import
--- PASS: TestAccPagerDutyEscalationPolicy_import (12.64s)
=== RUN   TestAccPagerDutyExtension_import
--- PASS: TestAccPagerDutyExtension_import (16.99s)
=== RUN   TestAccPagerDutyMaintenanceWindow_import
--- PASS: TestAccPagerDutyMaintenanceWindow_import (15.77s)
=== RUN   TestAccPagerDutySchedule_import
--- PASS: TestAccPagerDutySchedule_import (12.73s)
=== RUN   TestAccPagerDutyServiceIntegration_import
--- PASS: TestAccPagerDutyServiceIntegration_import (18.65s)
=== RUN   TestAccPagerDutyService_import
--- PASS: TestAccPagerDutyService_import (13.65s)
=== RUN   TestAccPagerDutyServiceWithIncidentUrgency_import
--- PASS: TestAccPagerDutyServiceWithIncidentUrgency_import (14.60s)
=== RUN   TestAccPagerDutyTeamMembership_import
=== RUN   TestAccPagerDutyTeamMembership_import
--- PASS: TestAccPagerDutyTeamMembership_import (13.40s)
=== RUN   TestAccPagerDutyTeam_import
--- PASS: TestAccPagerDutyTeam_import (8.27s)
=== RUN   TestAccPagerDutyUserContactMethod_import
--- PASS: TestAccPagerDutyUserContactMethod_import (12.34s)
=== RUN   TestAccPagerDutyUser_import
--- PASS: TestAccPagerDutyUser_import (11.38s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProviderImpl
--- PASS: TestProviderImpl (0.00s)
=== RUN   TestAccPagerDutyAddon_Basic
--- PASS: TestAccPagerDutyAddon_Basic (13.45s)
=== RUN   TestAccPagerDutyEscalationPolicy_Basic
--- PASS: TestAccPagerDutyEscalationPolicy_Basic (20.65s)
=== RUN   TestAccPagerDutyEscalationPolicyWithTeams_Basic
--- PASS: TestAccPagerDutyEscalationPolicyWithTeams_Basic (20.28s)
=== RUN   TestAccPagerDutyExtension_Basic
--- PASS: TestAccPagerDutyExtension_Basic (24.96s)
=== RUN   TestAccPagerDutyMaintenanceWindow_Basic
--- PASS: TestAccPagerDutyMaintenanceWindow_Basic (24.09s)
=== RUN   TestAccPagerDutySchedule_Basic
--- PASS: TestAccPagerDutySchedule_Basic (19.76s)
=== RUN   TestAccPagerDutyScheduleOverflow_Basic
--- PASS: TestAccPagerDutyScheduleOverflow_Basic (20.58s)
=== RUN   TestAccPagerDutySchedule_BasicWeek
--- PASS: TestAccPagerDutySchedule_BasicWeek (19.68s)
=== RUN   TestAccPagerDutySchedule_Multi
--- PASS: TestAccPagerDutySchedule_Multi (11.94s)
=== RUN   TestAccPagerDutyServiceIntegration_Basic
--- PASS: TestAccPagerDutyServiceIntegration_Basic (26.85s)
=== RUN   TestAccPagerDutyServiceIntegrationGeneric_Basic
--- PASS: TestAccPagerDutyServiceIntegrationGeneric_Basic (23.82s)
=== RUN   TestAccPagerDutyService_Basic
--- PASS: TestAccPagerDutyService_Basic (27.91s)
=== RUN   TestAccPagerDutyService_BasicWithIncidentUrgencyRules
--- PASS: TestAccPagerDutyService_BasicWithIncidentUrgencyRules (29.51s)
=== RUN   TestAccPagerDutyService_FromBasicToCustomIncidentUrgencyRules
--- PASS: TestAccPagerDutyService_FromBasicToCustomIncidentUrgencyRules (22.79s)
=== RUN   TestAccPagerDutyService_SupportHoursChange
--- PASS: TestAccPagerDutyService_SupportHoursChange (21.92s)
=== RUN   TestAccPagerDutyTeamMembership_Basic
--- PASS: TestAccPagerDutyTeamMembership_Basic (11.83s)
=== RUN   TestAccPagerDutyTeam_Basic
--- PASS: TestAccPagerDutyTeam_Basic (13.83s)
=== RUN   TestAccPagerDutyUserContactMethodEmail_Basic
--- PASS: TestAccPagerDutyUserContactMethodEmail_Basic (18.73s)
=== RUN   TestAccPagerDutyUserContactMethodPhone_Basic
--- PASS: TestAccPagerDutyUserContactMethodPhone_Basic (20.02s)
=== RUN   TestAccPagerDutyUserContactMethodSMS_Basic
--- PASS: TestAccPagerDutyUserContactMethodSMS_Basic (20.34s)
=== RUN   TestAccPagerDutyUser_Basic
--- PASS: TestAccPagerDutyUser_Basic (15.92s)
=== RUN   TestAccPagerDutyUserWithTeams_Basic
--- PASS: TestAccPagerDutyUserWithTeams_Basic (26.19s)
PASS
ok    github.com/terraform-providers/terraform-provider-pagerduty/pagerduty 645.402s

```

</p>
</details>

### CODE REVIEW

**Comment by heimweh** [comment]
Hi @gordonbondon, thank you so much for this :pray:

Would you mind updating it to beta2 instead, since it just got released? :slightly_smiling_face: 

Think it is `github.com/hashicorp/terraform@v0.12.0-beta2`

Thank you so much!

**Comment by gordonbondon** [comment]
@heimweh done!

**Comment by gordonbondon** [comment]
I've updated this PR to latest terraform sdk rc1.
@heimweh any idea when we can merge mentioned PRs so I can unWIP this one and get it merged too?

**Comment by limitusus** [comment]
Finally tf v0.12 is GA, we're eagerly waiting for get it released!

**Comment by heimweh** [comment]
Hi @gordonbondon! Sorry for the delay here. 
Would you mind updating again now when `0.12.0` is out? Thanks :pray:

**Comment by gordonbondon** [comment]
@heimweh updated to latest and rebased. Should be good to go.

**Pull request merged**
