### PR TITLE
Pagerduty team data source

### LINKED ISSUE #64: [Enhancement] pagerduty_team data source
Hi,

we've upgraded to `standard` and have found it to be much nicer to introduce terraform at the boundary of the teams. Meaning, we we want to create teams, schedules, users etc. by hand, but want to create services, service integrations etc. using terraform.

This is currently impossible without first performing an import of an existing resource. We'd much rather be able to just create new services and escalation policies using a data resource instead of a resource.. ehrm.. resource.

In short we'd like this:

```terraform
data "pagerduty_team" "team" {
    name = "${var.team_name}"
}
```

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.11.3
+ provider.aws v1.9.0
+ provider.pagerduty v0.1.3

### PR DESCRIPTION
**Pull request by paddie**
Initial work on the data source that would fix #64

### CODE REVIEW

**Comment by paddie** [comment]
It seems the tests run but I found writing them a bit confusing, so let me know if there's anything missing.

**Comment by rlhh** [comment]
👍 Would love to see this merged as it nicely complements the existing pagerduty_team resource

**Comment by heimweh** [comment]
Hi @paddie,

thank you so much for this contribution! 👍

This looks good to me at a first glance, left one comment regarding `Description`. 

Would you mind adding documentation for this resource as well? You’ll find a basic example here which is for the user data source: https://github.com/terraform-providers/terraform-provider-pagerduty/blob/master/website/docs/d/user.html.markdown

Again thank you so much for this! 🙂

**Comment by paddie** [comment]
@heimweh on it.

**Comment by paddie** [comment]
@heimweh Alright, I also added a `Description` alongside the required field and added a readme entry

**Comment by paddie** [comment]
@heimweh what's the status on this one?

**Comment by paddie** [comment]
@heimweh nice catch. Made the mentioned changes, maybe double check the `pagerduty.erb` changes for me.

**Comment by paddie** [comment]
Awesome, thanks for the excellent code review @heimweh !

**Pull request merged**
