### PR TITLE
r/pagerduty_schedule: Don't read back `start` value for schedule layers.

### PR DESCRIPTION
**Pull request by heimweh**
This PR fixes a bug found in `pagerduty_schedule` (described in #34) related to `start`.

The PagerDuty API always returns a new `start` value, 
which in turn causes Terraform to get a diff on every plan. 

This PR should resolve that, by ignoring whatever value we get back from the API.

### CODE REVIEW

**Comment by 2rs2ts** [comment]
👏 thanks for the super quick response on this issue!

**Comment by 2rs2ts** [comment]
Is there something holding this back from being merged?

**Comment by 2rs2ts** [comment]
The PagerDuty API doesn't really document the resources it exposes or any of their quirks, just the generic API methods available. https://v2.developer.pagerduty.com/docs/endpoints

I poked around the API and I believe it's not that the API always returns a new value, but rather, the start time is getting updated every time terraform updates the schedule. It may actually be that there's a way to prevent that from happening, but I'm not sure right now.

**Comment by heimweh** [comment]
@2rs2ts - Your observation is correct. The `start` time when updating a schedule layer will always be the time when the schedule layer was last updated, also confirmed this with the support team at PagerDuty.

@catsby - Unfortunately this behavior isn't documented anywhere, but I made an effort describing the behavior in the resource documentation. I don't think the updated value we get back from the API is of any real value, but it would in that case make more sense to store that updated value under a different name such as: `last_updated`. Would you mind taking a look again? many thanks! 🙇

**Comment by Nowaker** [comment]
Nice @heimweh!

**Pull request merged**
